export const ORDERS_REQUEST = "ORDERS_REQUEST/ORDERS_REQUEST";
export const ORDERS_UPDATE = "ORDERS_UPDATE/ORDERS_UPDATE";


export const ORDERS_DELIVERED_REQUEST = "ORDERS_REQUEST/ORDERS_DELIVERED_REQUEST";
export const ORDERS_DELIVERED_UPDATE = "ORDERS_UPDATE/ORDERS_DELIVERED_UPDATE";
export const ORDERS_DELIVERED_ERROR = "ORDERS_UPDATE/ORDERS_DELIVERED_ERROR";